name: Delete head branch after PR merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete-head-branch:
    if: ${{ github.event.pull_request.merged == true &&
            github.event.pull_request.head.repo.full_name == github.repository &&
            github.event.pull_request.head.ref != 'main' &&
            github.event.pull_request.head.ref != 'staging' }}
    runs-on: [self-hosted, Linux, X64, trusted, docker]
    steps:
      - name: Delete head branch via REST API
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const evtPayload = (typeof context !== 'undefined' && context.payload) ? context.payload : (github && github.context && github.context.payload) || {};
            const pr = evtPayload.pull_request;
            if (!pr) {
              core.info('No pull_request payload available — nothing to do.');
              return;
            }

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const headRef = pr.head && pr.head.ref;
            const fullHeadRepo = pr.head && pr.head.repo && pr.head.repo.full_name;
            core.info(`Attempting to delete branch '${headRef}' from ${fullHeadRepo}`);

            if (!headRef) {
              core.info('Head ref is not available — aborting.');
              return;
            }

            const ref = `heads/${headRef}`;

            try {
              await github.rest.git.deleteRef({ owner, repo, ref });
              core.info(`Deleted branch: ${headRef}`);
            } catch (err) {
              core.warning(`Could not delete branch '${headRef}': ${err.message || err}`);
            }
